// Copyright (C) 2005 - 2021 Settlers Freaks (sf-team at siedler25.org)
//
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#include "MapConsts.h"

constexpr unsigned MAX_OBSERVATION_WINDOWS = 50;

enum GUI_ID : unsigned
{
    CGI_ACTION,
    CGI_CHAT,
    CGI_DIRECTIPCONNECT,
    CGI_DIRECTIPCREATE,
    CGI_ENDGAME,
    CGI_LOBBYCONNECT,
    CGI_LOBBYADDSERVER,
    CGI_MAINSELECTION,
    CGI_MSGBOX,
    CGI_OPTIONSWINDOW,
    CGI_POSTOFFICE,
    CGI_ROADWINDOW,
    CGI_LOBBYSERVERINFO,
    CGI_README,
    CGI_DISTRIBUTION,
    CGI_BUILDORDER,
    CGI_TRANSPORT,
    CGI_PLAYREPLAY,
    CGI_MILITARY,
    CGI_TOOLS,
    CGI_SKIPGFS,
    CGI_INVENTORY,
    CGI_SAVE,
    CGI_PLEASEWAIT,
    CGI_MINIMAP,
    CGI_BUILDINGS,
    CGI_BUILDINGSPRODUCTIVITY,
    CGI_MUSICPLAYER,
    CGI_INPUTWINDOW,
    CGI_STATISTICS,
    CGI_ECONOMICPROGRESS,
    CGI_DIPLOMACY,
    CGI_SUGGESTPACT,
    CGI_SHIP,
    CGI_HELP,
    CGI_SETTINGS,
    CGI_ADDONS,
    CGI_MERCHANDISE_STATISTICS,
    CGI_MISSION_STATEMENT,
    CGI_MAP_DEBUG,
    CGI_AI_DEBUG,
    CGI_MAP_GENERATOR,
    CGI_VICTORY,
    CGI_OBSERVATION,
    CGI_BUILDING, /// Building windows use this as the base ID and add a unique number for each building
    CGI_NEXT = CGI_BUILDING + MAX_MAP_SIZE * MAX_MAP_SIZE
};
