#ifndef VERSION_DEFINE_H_INCLUDED
#define VERSION_DEFINE_H_INCLUDED

#define WINDOW_TITLE "Return To The Roots"
#define WINDOW_VERSION "20000211"
#define WINDOW_REVISION "0"

#endif // VERSION_DEFINE_H_INCLUDED
