// Copyright (c) 2017 - 2017 Settlers Freaks (sf-team at siedler25.org)
//
// This file is part of Return To The Roots.
//
// Return To The Roots is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 2 of the License, or
// (at your option) any later version.
//
// Return To The Roots is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Return To The Roots. If not, see <http://www.gnu.org/licenses/>.

#include "mapGenerator/MapSettings.h"
#include "gameData/MaxPlayers.h"
#include <boost/test/unit_test.hpp>

using namespace rttr::mapGenerator;

BOOST_AUTO_TEST_SUITE(MapSettingsTests)

BOOST_AUTO_TEST_CASE(MakeValid_sets_default_name_and_author)
{
    MapSettings settings;
    settings.MakeValid();
    BOOST_REQUIRE_EQUAL(settings.name, "Random");
    BOOST_REQUIRE_EQUAL(settings.author, "AutoGenerated");
}

BOOST_AUTO_TEST_CASE(MakeValid_ensures_valid_number_of_players)
{
    MapSettings settings;
    settings.numPlayers = 0;
    settings.MakeValid();
    BOOST_REQUIRE_EQUAL(settings.numPlayers, 1);

    settings.numPlayers = MAX_PLAYERS + 1;
    settings.MakeValid();
    BOOST_REQUIRE_EQUAL(settings.numPlayers, MAX_PLAYERS);
}

BOOST_AUTO_TEST_CASE(MakeValid_ensures_map_size_is_even)
{
    MapSettings settings;
    settings.size = MapExtent(17, 19);
    settings.MakeValid();
    BOOST_REQUIRE(settings.size.x % 2 == 0);
    BOOST_REQUIRE(settings.size.y % 2 == 0);
}

BOOST_AUTO_TEST_CASE(MakeValid_ensures_minimum_size_is_16_x_16)
{
    MapSettings settings;
    settings.size = MapExtent(14, 14);
    settings.MakeValid();
    BOOST_REQUIRE(settings.size == MapExtent(16, 16));
}

BOOST_AUTO_TEST_CASE(MakeValid_ensures_total_ratio_for_mountain_resources_is_at_least_1)
{
    MapSettings settings;
    settings.ratioCoal = 0;
    settings.ratioGold = 0;
    settings.ratioIron = 0;
    settings.ratioGranite = 0;
    settings.MakeValid();
    BOOST_REQUIRE(settings.ratioCoal + settings.ratioGold + settings.ratioIron + settings.ratioGranite > 0);
}

BOOST_AUTO_TEST_SUITE_END()
