INCLUDE("${CMAKE_CURRENT_LIST_DIR}/../Modules/CMakeMacroSetCCache.cmake")

# specify the cross compiler
SET_CCACHE(CMAKE_C_COMPILER i686-apple-darwin10-gcc)
SET_CCACHE(CMAKE_CXX_COMPILER i686-apple-darwin10-g++)
SET(CMAKE_RANLIB i686-apple-darwin10-ranlib CACHE STRING "" FORCE)
SET(CMAKE_LIPO i686-apple-darwin10-lipo CACHE STRING "" FORCE)

SET(OSX104_SDK "/usr/lib/apple/SDKs/MacOSX10.4u.sdk")
SET(OSX105_SDK "/usr/lib/apple/SDKs/MacOSX10.5.sdk")
#SET(OSX106_SDK "/usr/lib/apple/SDKs/MacOSX10.6.sdk")

# set SDK (use newest first)
SET(CMAKE_OSX_DEPLOYMENT_TARGET )
IF(EXISTS ${OSX105_SDK})
	SET(CMAKE_OSX_SYSROOT ${OSX105_SDK})
ELSEIF(EXISTS ${OSX104_SDK})
	SET(CMAKE_OSX_SYSROOT ${OSX104_SDK})
ELSE()
	MESSAGE(FATAL_ERROR "No OSX SDK found!")
ENDIF()
SET(CMAKE_OSX_SYSROOT ${CMAKE_OSX_SYSROOT} CACHE PATH "Path to OSX SDK")
MESSAGE(STATUS "Using OSX SDK at ${CMAKE_OSX_SYSROOT}")

SET(CMAKE_PREFIX_PATH ${CMAKE_OSX_SYSROOT})
SET(CMAKE_FIND_ROOT_PATH ${CMAKE_PREFIX_PATH})
SET(BOOST_ROOT ${CMAKE_PREFIX_PATH})

# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
