// Copyright (c) 2005 - 2020 Settlers Freaks (sf-team at siedler25.org)
//
// This file is part of Return To The Roots.
//
// Return To The Roots is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 2 of the License, or
// (at your option) any later version.
//
// Return To The Roots is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Return To The Roots. If not, see <http://www.gnu.org/licenses/>.

#include "mapGenerator/MapSettings.h"
#include "helpers/mathFuncs.h"
#include "gameData/MaxPlayers.h"

namespace rttr { namespace mapGenerator {

    void MapSettings::Validate()
    {
        if(name.empty())
            name = "Random";
        if(author.empty())
            author = "AutoGenerated";

        numPlayers = helpers::clamp(numPlayers, 1u, MAX_PLAYERS);
        // Even map size
        size.x &= ~1;
        size.y &= ~1;
        size = elMax(size, MapExtent::all(16));
        if(ratioGold + ratioIron + ratioCoal + ratioGranite == 0)
            ratioCoal = 1;
    }

}} // namespace rttr::mapGenerator
