IF ( NOT ${OSX_SDK} STREQUAL "" )
    SET(BOOST_ROOT ${OSX_SDK})
	FORCE_ADD_FLAGS(CMAKE_C_FLAGS -isysroot ${OSX_SDK})
	FORCE_ADD_FLAGS(CMAKE_CXX_FLAGS -isysroot ${OSX_SDK})

	FORCE_ADD_FLAGS(CMAKE_EXE_LINKER_FLAGS -isysroot ${OSX_SDK})
	FORCE_ADD_FLAGS(CMAKE_MODULE_LINKER_FLAGS -isysroot ${OSX_SDK})
	FORCE_ADD_FLAGS(CMAKE_SHARED_LINKER_FLAGS -isysroot ${OSX_SDK})
ENDIF ( NOT ${OSX_SDK} STREQUAL "" )

# disable optimization - buggy gcc?
FORCE_ADD_FLAGS(CMAKE_CXX_FLAGS_MINSIZEREL -O0 -DNDEBUG)
FORCE_ADD_FLAGS(CMAKE_CXX_FLAGS_RELEASE -O0 -DNDEBUG)
FORCE_ADD_FLAGS(CMAKE_CXX_FLAGS_RELWITHDEBINFO -O0 -g)

SET(CMAKE_OSX_SYSROOT ${OSX_SDK} CACHE PATH "" FORCE)
