DetectOSXArchs()
SET(CMAKE_OSX_ARCHITECTURES "${DETECTED_OSX_ARCHS}" CACHE STRING "OSX-Architectures" FORCE)

IF(CMAKE_VERSION VERSION_LESS 3.4)
    SET(CMAKE_FIND_LIBRARY_SUFFIXES ".tbd;.dylib;.so;.a" CACHE STRING "Library Suffixes" FORCE)
ENDIF()
