# disable optimization - buggy gcc?
#FORCE_ADD_FLAGS(CMAKE_CXX_FLAGS_MINSIZEREL -O0 -DNDEBUG)
#FORCE_ADD_FLAGS(CMAKE_CXX_FLAGS_RELEASE -O0 -DNDEBUG)
#FORCE_ADD_FLAGS(CMAKE_CXX_FLAGS_RELWITHDEBINFO -O0 -g)
