# this one is important
EXECUTE_PROCESS(COMMAND "uname" OUTPUT_VARIABLE CMAKE_SYSTEM_NAME OUTPUT_STRIP_TRAILING_WHITESPACE)
EXECUTE_PROCESS(COMMAND "uname" "-m" OUTPUT_VARIABLE CMAKE_SYSTEM_PROCESSOR OUTPUT_STRIP_TRAILING_WHITESPACE)

# specify the compiler
#SET_CCACHE(CMAKE_C_COMPILER   cc)
#SET_CCACHE(CMAKE_CXX_COMPILER c++)

INCLUDE(cmake/freebsd.common.cmake)
